spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grafana
        image: ${fabric8.dockerUser}grafana:2.6.1
        env:
        - name: PROMETHEUS_ADDRESS
          value: http://prometheus
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/grafana
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: grafana-data
