---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
  name: "taiga-back"
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    provider: "fabric8"
    project: "taiga"
