apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: fabric8/fluentd-kubernetes:${fabric8-fluentd-kubernetes.version}
        name: fluentd
        ports:
          - name: scrape
            containerPort: 24231
        env:
          - name: ELASTICSEARCH_HOST
            value: elasticsearch
          - name: ELASTICSEARCH_PORT
            value: "9200"
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: defaultdocker
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: awsdocker
            mountPath: /mnt/ephemeral/docker/containers
            readOnly: true
          - name: minikubedocker
            mountPath: /mnt/sda1/var/lib/docker/containers
            readOnly: true
        resources:
          limits:
            cpu: 100m
        securityContext:
          privileged: true
      serviceAccountName: fluentd
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: defaultdocker
          hostPath:
            path: /var/lib/docker/containers
        - name: awsdocker
          hostPath:
            path: /mnt/ephemeral/docker/containers
        - name: minikubedocker
          hostPath:
            path: /mnt/sda1/var/lib/docker/containers
