---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "letschat"
  labels:
    provider: "fabric8"
    expose: "true"
  annotations:
    fabric8.io/app-menu: development
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: "letschat"
