---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sonarqube"
  annotations:
    fabric8.io/app-menu: development
  labels:
    provider: "fabric8"
    expose: "true"
spec:
  ports:
  - port: 9000
    protocol: "TCP"
    targetPort: 9000
  selector:
    name: "sonarqube"
