---
apiVersion: "v1"
data:
  hubot-password: "RedHat$1"
  hubot-username: "fabric8"
  letschat-default-rooms: "fabric8_default"
  hubot-token: ""
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"HUBOT_USERNAME\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The username for Hubot to login to the chat service\",\n      \"default\"\
      \ : \"fabric8\"\n    },\n    \"LETSCHAT_DEFAULT_ROOMS\" : {\n      \"type\"\
      \ : \"string\",\n      \"description\" : \"Default rooms to create and for hubot\
      \ to join\",\n      \"default\" : \"fabric8_default\"\n    },\n    \"HUBOT_PASSWORD\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The password\
      \ for Hubot to login to the chat service\",\n      \"default\" : \"RedHat$1\"\
      \n    }\n  }\n}"
  labels:
    name: "letschat"
    provider: "fabric8"
  name: "letschat"
