spec:
  replicas: ${replicas}
  template:
    spec:
      containers:
      - name: kibana
        image: ${fabric8.dockerUser}kibana4:v${kibana.version}
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            port: 5601
            path: /
          initialDelaySeconds: 5
      - name: logstash-template
        image: ${fabric8.dockerUser}kibana-config:${project.version}
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
