metadata:
  name: kibana
  labels:
    provider: "fabric8"
    expose: "true"
  annotations:
    fabric8.io/app-menu: management
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5601
