apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
data:
  config.yml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
