---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
  name: "gitlab-ssh"
spec:
  ports:
  - port: 22
    protocol: "TCP"
    targetPort: 22
  selector:
    project: "gitlab"
    provider: "fabric8"
