---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
  name: "hubot-jenkins-notifier"
spec:
  ports:
  - port: 5555
    protocol: "TCP"
    targetPort: 5555
  selector:
    project: "hubot-letschat"
    provider: "fabric8"
