spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: metrics
      containers:
      - name: prometheus
        image: prom/prometheus:v1.3.1
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /prometheus
          subPath: prometheus-db
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
      - name: configmap-reload
        image: jimmidyson/configmap-reload:v0.1
        args:
          - -volume-dir
          - /etc/prometheus
          - -webhook-url
          - http://localhost:9090/-/reload
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data-volume
        persistentVolumeClaim:
          claimName: prometheus-data
