metadata:
  annotations:
    prometheus.io/scrape: "true"
    fabric8.io/app-menu: management
  labels:
    provider: "fabric8"
    expose: "true"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090
