---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    expose: "true"
  name: "gerrit-ssh"
spec:
  ports:
  - port: 29418
    protocol: "TCP"
    targetPort: 29418
  selector:
    project: "gerrit"
    provider: "fabric8"
