spec:
  replicas: ${replicas}
  template:
    spec:
      containers:
      - name: elasticsearch
        image: ${fabric8.dockerUser}elasticsearch-k8s:${elasticsearch.version}
        env:
          - name: SERVICE
            value: elasticsearch-masters
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            port: 9200
            path: /_template/logstash
          initialDelaySeconds: 5
      - name: logstash-template
        image: ${fabric8.dockerUser}elasticsearch-logstash-template:${project.version}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: es-data
